
source .env && 
gcloud builds submit  \
    --substitutions=_PROJECT=$PROJECT,_IMAGE_SOURCE=$IMAGE_SOURCE,_REGION=$REGION,_MIN_INSTANCES=$MIN_INSTANCES,_MAX_INSTANCES=$MAX_INSTANCES,_CONCURRENCY=$CONCURRENCY,_CPU=$CPU,_MEMORY=$MEMORY,_IMAGOR_SECRET=$IMAGOR_SECRET,_GCLOUD_RESULT_STORAGE_BUCKET=$GCLOUD_RESULT_STORAGE_BUCKET,_GCLOUD_RESULT_STORAGE_BASE_DIR=$GCLOUD_RESULT_STORAGE_BASE_DIR \
    --project $PROJECT \
    --async \
    --config cloudbuild.yaml \
    .
